### ISSUE TITLE
Auto DNS on Windows

### ISSUE THREAD

**Issue by AgarvaiN** [cytopia/devilbox#101]
I'm having issue with Auto DN S(Bind) on Windows Machine

Docker version 17.05.0-ce, build 89658be
docker-compose version 1.13.0, build 1719ceb8
Using Docker Toolbox on Windows

My LOCAL_LISTEN_ADDR=192.168.137.130: 
DNS Server are set to 192.168.137.130; 8.8.4.4; 8.8.8.8 In my Network Config

And everything works except for Auto DNS option, which i'd really like, because editing /etc/hosts on Windows is slightly annoying.

When I do edit it, it does propagate properly, so I can confirm everything is working on that side.

But DNS Server is not accessible through 192.168.137.130, I tested it as standalone, and internet becomes inaccessible completely.  

Anyways, I saw you are planning on including some Windows related fixes, so you might want to include this as well.

Not sure where exactly does the issue occur, or if I'm not doing something properly(Although I think I covered the most of it), so if anything else is needed, let me know I'll provide further details.

**Comment by cytopia** [comment]
@AgarvaiN this is an issue related to how [Docker Toolbox](https://www.docker.com/products/docker-toolbox) works. It only works via (afaik) a VirtualBox middle man that provides the actual docker functionality.

The `httpd` server has an internal IP address (inside the toolbox): `172.16.238.11` to which the DNS server is resolving the `TLD_SUFFIX` domains to, however this IP address does not seem to be reachable from your host computer, because you would need it to point to `192.168.137.130` (The VirtualBox host). If you changed this value of the DNS server in docker-compose.yml, the the `php` docker won't be able to issue DNS queries anymore, because it still expects it to go to `172.16.238.11`.

Hope this is somehow understandable (a little bit complicated to explain for me).


However, it should work if you use the native Docker for windows: [Docker for Windows](https://docs.docker.com/docker-for-windows/install/). Could you give this a try instead of the old Toolbox.

In the mean-time I will think a bit if it can be accomplished with the toolbox via some port-forwarding.

**Comment by cytopia** [comment]
I might have a workaround:

In `docker-compose.yml` edit `WILDCARD_ADDRESS`,  `DNS_FORWARDER` and `FORWARD_PORTS_TO_LOCALHOST` with the following values:
```yml
bind:
  ...
    environment:
      - WILDCARD_ADDRESS=127.0.0.1
      - DNS_FORWARDER=${BIND_DNS_RESOLVER:-8.8.8.8,8.8.4.4}

php:
  ...
    environment:
      - FORWARD_PORTS_TO_LOCALHOST=80:httpd:80,3306:mysql:3306,5432:pgsql:5432,6379:redis:6379,11211:memcd:11211,27017:mongo:27017,5672:rabbit:5672,15672:rabbit:15672
```

Then the only thing left to do for you is to forward port `80` from `192.168.137.130` to your hosts `127.0.0.1` address
