### ISSUE TITLE
docker-sync support

### ISSUE THREAD

**Issue by bsormagec** [cytopia/devilbox#105]
I think docker-sync support will be good for mac because docker has poor performance on osx. Can you add this to devilbox ?

**Comment by cytopia** [comment]
@bsormagec thanks for pointing it out. Can you direct me to some more documentation about this.

**Comment by bsormagec** [comment]
Sure,

https://github.com/EugenMayer/docker-sync/wiki/2.-Configuration

**Comment by vzlatev** [comment]
Hello,

Any plans to include it in the upcoming releases - on OSX without docker-sync web apps are awfully slow.

Regards

**Comment by richdel** [comment]
+1, without docker-sync there are a couple of options for os x when mounting shares using bind mounts:

- consistent or default: The default setting with full consistency, as described above.
- delegated: The container runtime’s view of the mount is authoritative. There may be delays before updates made in a container are visible on the host.
- cached: The macOS host’s view of the mount is authoritative. There may be delays before updates made on the host are visible within a container.

(Source: https://docs.docker.com/engine/admin/volumes/bind-mounts/#configure-mount-consistency-for-macos)
 
Unfortunately though none of them appear to resolve the bi-directional sync without huge performance overheads (in the case of the default consistent setting) or persistence issues (e.g. if uploading images to a cms and building up a site's content locally with the docker container instance). Using vagrant in the past for large Magento builds I tried both unison and gatling-rsync, the latter being more performant and the final solution chosen which worked wonders. It ended up being a v similar setup to the docker-sync native_osx implementation, more reading material here:

- http://docker-sync.io/
- https://github.com/EugenMayer/docker-sync
- https://github.com/EugenMayer/docker-sync/wiki/How-does-native_osx-work-with-OSXFS-and-is-still-native-speed-fast%3F

As an aside and a short term workaround to resolve performance issues at the moment is to use memcache/redis caching which works really well, managed to get a basic WordPress instance sub 80ms fully rendered in the browser!

**Comment by mad99** [comment]
Any news about a well usable and reasonably fast system under osx? 

Have tried to extend the Makefile  on my own (process to include docker-sync-stack). But it does not work well... 
Maybe someone else is also to try to do this way. Would great to share or hear from news in this directions!

**Comment by cytopia** [comment]
This is still on the agenda, however the roadmap is currently really filled and me alone working on that takes some time. Probably somebody wants to jump in on this issue and submit a PR.

**Comment by johnwbaxter** [comment]
I tried setting up docker-sync but ended up somehow making docker use 400% cpu...will try again though as it's almost unusable on OSX as it stands.

**Comment by johnwbaxter** [comment]
@cytopia What would it cost to sponsor you to move this to the top of the list?

**Comment by cytopia** [comment]
@johnwbaxter I'd rather have someone helping me on this issue, as I dont' have a Mac at the moment. So I cannot get sponsored on this one and make an unreliable promises/guess. But thank you for bringing this up.

**Comment by cytopia** [comment]
@bsormagec @vzlatev @richdel @mad99 @johnwbaxter 

The above suggestion should now be easily achievable via global mount options: https://devilbox.readthedocs.io/en/latest/configuration-files/env-file.html#mount-options

**Comment by ericfynnmaier** [comment]
Has anyone solved this problem by using docker-sync or the global mount options? If yes, could you please tell us your configuration? Thanks in advance!

**Comment by cytopia** [comment]
@ericfynnmaier have you already tried one of these:

```
MOUNT_OPTIONS=,consistent
MOUNT_OPTIONS=,cached
MOUNT_OPTIONS=,delegated
```

Probably `,cached` will give you some performance boost. I have no OSX anymore to try. Can you give it a shot and report how well it performs in terms of the empty default

**Comment by ericfynnmaier** [comment]
@cytopia thank you! I added `,cached` to the .env and e.g. Wordpress loads way faster!

**Comment by vielhuber** [comment]
```,cached``` only seems to improve performance on mac, but not windows.
how do windows people work with devilbox in a performant manner?

**Comment by cytopia** [comment]
@vielhuber I haven't looked into Windows yet for those kinds of performance improvements. Any idea what alternatives are offered for Windows

**Comment by vielhuber** [comment]
The only tool everybody is mentionning is "docker-sync" (http://docker-sync.io/).
This seems to solve the problems everywhere.

**Comment by cytopia** [comment]
OK, didn't know that this also works on Windows.

**Comment by vielhuber** [comment]
On which OS do you work?
Do you also suffer from performance problems like everybody else when spinning up a normal Laravel project?

**Comment by cytopia** [comment]
I started this project on OSX and am now on Debian Linux. So far no performance issues.

**Comment by jeffwhitfield** [comment]
I would **love** to know how to get docker-sync working with Devilbox. Running Magento on my Mac is absolutely atrocious! Tried everything but docker-sync which, based on what I'm reading, will result in a serious performance bump.

**Comment by anselmdk** [comment]
Just adding myself here. I spent the day yesterday getting up to speed with Devilbox (I absolutely LOVE it -great work!), however I'm also experiencing performance issues on the Mac...

**Comment by krebbi** [comment]
What about using SSHFS to access the dockers document root from the host? 

https://github.com/libfuse/sshfs

**Comment by chiribuc** [comment]
Hi guys,

I think I successfully installed docker sync on my Mac.  
This are the steps to make it work on your Mac OS machine:  

### Step 1.
Install docker-sync:
```bash
gem install docker-sync
```

Install `unison`:
```bash
brew install unison
brew install eugenmayer/dockersync/unox
```

### Step 2.
Go to your `devilbox` directory, where you have the `docker-compose.yml` file and create two new files, `docker-sync.yml` and `docker-compose-dev.yml`.

In the `docker-sync.yml` file paste in the following but make sure to change the volume names and paths to reflect you local structure:
```yml
version: '2.1'

options:
    # the path to devilbox docker-compose.yml file
    compose-file-path: 'docker-compose.yml'
    
    # the path to your custom docker-compose-dev.yml file
    compose-dev-file-path: 'docker-compose-dev.yml'

syncs:
    # this name has to be unique and is used in docker-compose-dev.yml as well
    wordpress-sync:
        # which folder to watch / sync from - you can use tilde (~), it will get expanded. Be aware that the trailing slash makes a difference
        # if you add them, only the inner parts of the folder gets synced, otherwise the parent folder will be synced as top-level folder
        src: '~/data/www/wordpress/'
        
        # this does not user groupmap but rather configures the server to map
        # optional: usually if you map users you want to set the user id of your application container here
        sync_userid: '1000'
        
        # optional, default can be either rsync or unison See Strategies in the wiki for explanation
        sync_strategy: 'unison'
        
        # optional, a list of excludes. These patterns will not be synced
        # see http://www.cis.upenn.edu/~bcpierce/unison/download/releases/stable/unison-manual.html#ignore for the possible syntax and see sync_excludes_type below
        sync_excludes: ['.gitignore', '.git/', '.idea/', '.vscode/']
       
    # other app here 
    other-app-sync:
        src: '~/data/www/other-app/'
        sync_userid: '1000'
        sync_strategy: 'unison'
        sync_excludes: ['.gitignore', '.git/', '.idea/']
        
    # and so on...
```

In the `docker-compose-dev.yml` paste in the following but make sure to change the volume names and paths to reflect you local structure:
```yml
version: '2.1'
services:

bind:
    volumes: 
        # set the apps that you want to sync
        - wordpress-sync:/shared/httpd/wordpress:nocopy
        - other-app-sync:/shared/httpd/other-app:nocopy

volumes:
    # set each app volume as external
    wordpress-sync:
        external: true
    other-app-sync:
        external: true
```

### Step 3.
Run docker with docker sync using:
```bash
docker-sync-stack start
```

To stop the devilbox  `ctr+c` like always and `docker-sync stop`.
I have an alias for this in my `zsh`.

It's working for me so I hope will work for you.

**Comment by chiribuc** [comment]
P.S. - It seems that for me it works even better if I use `native_osx` as `sync_strategt` in the `docker-sync.yml` file.

**Comment by cytopia** [comment]
@chiribuc 
This is really great news. I've also linked it here in case someone stumbles across this issue via the forum: https://devilbox.discourse.group/t/fix-macos-performance-issues-via-docker-sync-mvp-available/72

Btw, if you do have bigger applications, can you tell something on the performance gain with docker-sync in place vs without.

**Comment by chiribuc** [comment]
> @chiribuc
> This is really great news. I've also linked it here in case someone stumbles across this issue via the forum: https://devilbox.discourse.group/t/fix-macos-performance-issues-via-docker-sync-mvp-available/72
> 
> Btw, if you do have bigger applications, can you tell something on the performance gain with docker-sync in place vs without.

I will try these days but at a simple look, the speed increased with more than 1 second.

**Comment by chiribuc** [comment]
If it helps, this is my personal set-up for now:

My `docker-sync.yml` file:
```yml
version: '2.1'

options:
    compose-file-path: 'docker-compose.yml'
    compose-dev-file-path: 'docker-compose-dev.yml'
    verbose: true

syncs:
    wordpress-sync:
        src: '~/code/docker/www/wordpress/' 
        sync_host_ip: 'auto'
        sync_userid: '501' # You can find your user id by typing `id -u` in the terminal
        sync_strategy: 'native_osx' # I use native_osx 'cause its faster for me.
        sync_excludes: ['.gitignore', '.git/', '.idea/', '.vscode/']

    quantum-sync:
        src: '~/code/docker/www/quantum/'
        sync_host_ip: 'auto'
        sync_userid: '501' # You can find your user id by typing `id -u` in the terminal
        sync_strategy: 'native_osx' # I use native_osx 'cause its faster for me.
        sync_excludes: ['.gitignore', '.git/', '.idea/', '.vscode/']

```

My `docker-compose-dev.yml` file:
```yml
version: '2.1'
services:
    bind:
        volumes:
            - wordpress-sync:/shared/httpd/wordpress:nocopy
            - quantum-sync:/shared/httpd/quantum:nocopy

    # -----------------------------------------------------------------------
    # This allows me to symlink any local directory into my projects
    #, For example, I have a WordPress container running but I develop my
    # plugins locally in some other directory than the one used by devilbox
    # so in order to symlink those plugins this is needed.
    php:
        volumes:
            - $HOME:$HOME
    httpd:
        volumes:
            - $HOME:$HOME
    # -----------------------------------------------------------------------

volumes:
    wordpress-sync:
        external: true
    quantum-sync:
        external: true
```

I will come back with some test results soon.

**Comment by cytopia** [comment]
> In the `docker-compose-dev.yml` paste in the following but make sure to change the volume names and paths to reflect you local structure:
> 
> ```yaml
> version: '2.1'
> services:
> 
> bind:
>     volumes: 
>         # set the apps that you want to sync
>         - wordpress-sync:/shared/httpd/wordpress:nocopy
>         - other-app-sync:/shared/httpd/other-app:nocopy
> 
> volumes:
>     # set each app volume as external
>     wordpress-sync:
>         external: true
>     other-app-sync:
>         external: true
> ```

@chiribuc why are you overwriting `bind` in `docker-compose-dev.yml` and not the `httpd` and `php` container which actually specifiy the mounts? `bind` does not have any volumes anyway.

So I was thinking of something like this instead:
```yml
version: '2.1'

services:
  php:
    volumes:
      - devilbox-intranet-sync:/var/www/default:nocopy
      - devilbox-data-www-sync:/shared/httpd:nocopy
  httpd:
    volumes:
      - devilbox-intranet-sync:/var/www/default:nocopy
      - devilbox-data-www-sync:/shared/httpd:nocopy

volumes:
  # set each app volume as external
  devilbox-intranet-sync:
    external: true
  devilbox-data-www-sync:
    external: true
```

With the following `docker-sync.yml`:

```yml
version: '2'

options:
  compose-file-path: 'docker-compose.yml'
  compose-dev-file-path: 'docker-compose-dev.yml'

syncs:
  devilbox-data-www-sync:
    src: 'data/www/'
    sync_userid: '1000'
    sync_strategy: 'unison'
    sync_excludes: ['.gitignore', '.git/', '.idea/', '.vscode/']

  devilbox-intranet-sync:
    src: '.devilbox/www:/var/www/default/'
    sync_userid: '1000'
    sync_strategy: 'unison'
    sync_excludes: ['.gitignore', '.git/', '.idea/', '.vscode/']
```

Also note that `docker-sync.yml` did not allow me to specify `version: '2.1'`, it asks for `version: '2'`
