### ISSUE TITLE
How to install additional software in the containers

### ISSUE THREAD

**Issue by mavimedia** [cytopia/devilbox#158]
I want to install some additional software like nano or something else.

I tried this in docker-compose.yml

```
  # ------------------------------------------------------------
  # PHP / HHVM
  # ------------------------------------------------------------
  php:
    image: cytopia/${PHP_SERVER:-php-fpm-7.0}:latest
    
    command: bash -c "apt-get update && apt-get -y install nano"

    restart: always
```
but it doesn't work

How can i do that?

UPDATE:
```
command: bash -c "yum install nano"
```
doesn't work, too
