### ISSUE TITLE
do you know about blackfire ?

### ISSUE THREAD

**Issue by bigxu** [cytopia/devilbox#236]
i looked https://github.com/AsgardCms/Platform/blob/3.0/docker-compose.yml had added blackfire.
would you add some software like blackfire ?

**Comment by cytopia** [comment]
## Add custom services

It is now possible to add your custom services to the Devilbox without having to touch the main `docker-compose.yml`. Use that for now.

Read more about it here:
* http://devilbox.readthedocs.io/en/latest/configuration-files/docker-compose-override-yml.html
* http://devilbox.readthedocs.io/en/latest/tutorials/add-your-own-docker-image.html

## A working example for blackfire:

**docker-compose.override.yml**
```yml
version: '2.1'
services:
  blackfire:
    image: blackfire/blackfire
    environment:
      BLACKFIRE_SERVER_ID:
      BLACKFIRE_SERVER_TOKEN:
    networks:
      app_net:
        ipv4_address: 172.16.238.200
    depends_on:
      - bind
      - php
      - httpd
```

**.env**
```bash
BLACKFIRE_SERVER_ID=
BLACKFIRE_SERVER_TOKEN
```

## Roadmap

I have added it to the Roadmap: https://github.com/cytopia/devilbox/issues/23
