### ISSUE TITLE
Submitting Elasticsearch Docker Example

### ISSUE THREAD

**Issue by science695** [cytopia/devilbox#360]
I saw elasticsearch on your roadmap and thought I'd submit my example docker usage of elasticsearch.

(This is a legacy configuration, and not in docker compose, but the core concepts are there):
```
docker run \
        -d  \
        --network elastic \
        --restart=always \
        -p 9200:9200 \
        -p 9300:9300 \
        -e "TZ=America/New_York" \
        -e "discovery.type=single-node" \
        -v "/etc/elasticsearch/config/files:/usr/share/elasticsearch/config/files" \
        -e "path.data=/var/lib/elasticsearch" \
        -v "/var/lib/elasticsearch:/var/lib/elasticsearch" \
        -e "path.logs=/var/log/elasticsearch" \
        -v "/var/log/elasticsearch:/var/log/elasticsearch" \
        --name elastic \
        docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.3
```

```
docker run \
        -d \
        --network elastic \
        --restart=always \
        -p 80:5601 \
        -e "TZ=America/New_York" \
        -e "ELASTICSEARCH_URL=http://elastic:9200" \
        --name kibana \
        docker.elastic.co/kibana/kibana-oss:6.2.3
```

```
docker run \
        -d \
        --network elastic \
        --restart=always \
        -p 9600:9600 \
        -e "TZ=America/New_York" \
        -e "PATH_DATA=/var/lib/logstash" \
        -v /var/lib/logstash:/var/lib/logstash \
        -e "PATH_CONFIG=/etc/logstash/conf.d" \
        -v /etc/logstash/:/etc/logstash \
        -e "PATH_LOGS=/var/log/logstash" \
        -v /var/log/logstash:/var/log/logstash \
        -e "LOG_LEVEL=info" \
        -e "HTTP_HOST=0.0.0.0" \
        -e "HTTP_PORT=9600" \
        -e "CONFIG_RELOAD_AUTOMATIC=true" \
        -e "CONFIG_RELOAD_INTERVAL=300" \
        -e "DB_HOST=DATABASE-SERVER" \
        --name logstash \
        custom/logstash-oss:6.2.3
```
I did have to make a custom image for logstash due to some difficulty with my mysql-connector-java.jar
```
FROM docker.elastic.co/logstash/logstash-oss:6.2.3
RUN logstash-plugin install logstash-input-jdbc
ADD mysql-connector-java.jar /usr/lib/java/mysql-connector-java.jar
```

`docker build --tag custom/logstash-oss:6.2.3`

**Comment by cytopia** [comment]
Thanks for that. I will have a look and integrate it.

**Comment by tracyfloyd** [comment]
Elasticsearch support would be awesome!

**Comment by cytopia** [comment]
@science695 is there a reason why you chose the `oss` versions? On their official Docker page I can't find any of those `oss` versions: https://www.docker.elastic.co

**Comment by cytopia** [comment]
@tracyfloyd @science695 @tzimpel @henkesn @llaville

Do you guys plan on using an APM agent (such as: https://github.com/philkra/elastic-apm-php-agent) to pump project performance metrics via [Elastic APM server](https://www.elastic.co/guide/en/apm/get-started/current/overview.html) into ES/Kibana?

**Comment by llaville** [comment]
I will share my contribution here about Elasticsearch Container.
I use official docker images with docker compose like that : 

```
  elasticsearch:
    # https://hub.docker.com/_/elasticsearch/
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.12
    hostname: elasticsearch
    ports:
      - "${LOCAL_LISTEN_ADDR}9200:9200"
      - "${LOCAL_LISTEN_ADDR}9300:9300"
    environment:
      - "http.host=${LOCAL_LISTEN_ADDR:-0.0.0.0}"
      - xpack.security.enabled=false
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - Des.scripting.exception_for_missing_value=true
    networks:
      app_net:
        ipv4_address: 172.16.238.240
    volumes:
      - ${DEVILBOX_PATH}/data/es:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
```

And a cool client web client => https://github.com/appbaseio/dejavu

With it's own docker-compose : 
```
  dejavu:
    # https://hub.docker.com/r/appbaseio/dejavu/
    image: appbaseio/dejavu:latest
    ports:
     - "1358:1358"
    networks:
      app_net:
        ipv4_address: 172.16.238.241
    links:
      - elasticsearch
```
