### ISSUE TITLE
Granular Configuration

### ISSUE THREAD

**Issue by science695** [cytopia/devilbox#413]
#### ISSUE TYPE
 - Feature request

#### SUMMARY
I keep seeing more and more feature requests for things that include very granular settings per project. (i.e.: having custom TLDs per project, different php versions per project, etc....)

I had an idea and wanted to share it with you in case it was helpful:

This level of setting is more than a env file and docker-compose.yml file can handle. But if you had an extra set of configuration that could be per project you might be able to open up a larger number of possible configurations.

i.e.:
```
global.yml:
  _default:
     - TLD
     - phpversion
     - docroot
     - ....
  site1:
     - domain
     - phpversion
     - docroot
     - ....
  site2:
     - domain
     - phpversion
     - docroot
```

Or possibly a config.yml file in each project to make it easier to configure each project seperately.

Then the bind server, and the web server would be able to parse these files and do more specific settings.

#### Goal
Make Devilbox easier to customize critical settings on a per project basis.
Remove the limitation of 1 global env / docker-compose.yml file.

Let me know if you would like me to clarify anything about this concept. And if its to complicated, *shrug*. I just thought I'd share it.

Thanks for all the work you put into this.
