### ISSUE TITLE
add_your_own_docker_image not joining devilbox networks?

### ISSUE THREAD

**Issue by jondkelley** [cytopia/devilbox#466]
### ISSUE TYPE

 - Bug Report

### Checklist

* [x ] `.env` file is attached

[env.txt](https://github.com/cytopia/devilbox/files/2738112/env.txt)

* [x ] `docker-compose.override.yml` is attached (if it exists)

[docker-compose.override.yml.txt](https://github.com/cytopia/devilbox/files/2738125/docker-compose.override.yml.txt)

* [x ] I've looked through the docs: https://devilbox.readthedocs.io/en/latest/
* [x ] I've looked through existing issues: https://github.com/cytopia/devilbox/issues

### OS / ENVIRONMENT

1. Host operating system and version: Macintosh,
2. (Windows) Native Docker or Docker Toolbox:  None
3. Docker version:  Docker 18.03, 
4. Docker Compose version: Compose 1.21.1
5. (Linux) Is SELinux enabled?: No
6. What git commit hash are you on?: 40d9bd1b853a940469bad5427bad07fcad2802fe

### SUMMARY

I can't add an additional unrelated host to my docker-compose.override.yml as indicated by the docs. I've reviewed `add_your_own_docker_image` and `overwrite_existing_docker_image` for advice.

### STEPS TO REPRODUCE

See my docker-compose.override.yml

### EXPECTED BEHAVIOUR

My container starts with the devilbox network `app_net`

### ACTUAL BEHAVIOUR

Bringing up my container mysql_seed acquires IP 127.17.0.2. Docker network inspect for devilbox_app_net shows only `httpd`, `memcd`, `mysql`, `bind`, `php` and is missing my container. 

```
bash-4.2# ifconfig
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 172.17.0.2  netmask 255.255.0.0  broadcast 172.17.255.255
        ether 02:42:ac:11:00:02  txqueuelen 0  (Ethernet)
        RX packets 24173  bytes 35163688 (33.5 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 11265  bytes 619958 (605.4 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        loop  txqueuelen 1  (Local Loopback)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```

#### Start command

```
docker-compose up -d  mysql_seed
```

#### File and user permissions (Linux & MacOS)

```
$ id
```

```
drwxr-xr-x  28 jon  staff    896 Jan  8 13:47 .
drwxr-xr-x   9 jon  staff    288 Jan  8 09:55 ..
drwxr-xr-x   5 jon  staff    160 Jan  2 17:14 .devilbox
-rw-r--r--   1 jon  staff  17220 Jan  7 16:45 .env
-rw-r--r--   1 jon  staff  17221 Jan  7 16:38 .env.bak
-rw-r--r--   1 jon  staff     41 Jan  2 17:14 .git
drwxr-xr-x   4 jon  staff    128 Jan  2 17:14 .github
-rw-r--r--   1 jon  staff   3656 Jan  2 17:14 .gitignore
drwxr-xr-x   8 jon  staff    256 Jan  2 17:14 .tests
-rw-r--r--   1 jon  staff   9510 Jan  2 17:14 .travis.yml
-rw-r--r--   1 jon  staff    894 Jan  2 17:14 CONTRIBUTING.md
-rw-r--r--   1 jon  staff   1064 Jan  2 17:14 LICENSE.md
-rw-r--r--   1 jon  staff  53973 Jan  2 17:14 README.md
drwxr-xr-x   4 jon  staff    128 Jan  2 17:14 autostart
drwxr-xr-x@  4 jon  staff    128 Jan  3 11:18 backups
drwxr-xr-x   4 jon  staff    128 Jan  2 17:14 bash
drwxr-xr-x@  6 jon  staff    192 Jan  3 11:18 ca
drwxr-xr-x  49 jon  staff   1568 Jan  3 14:45 cfg
drwxr-xr-x   8 jon  staff    256 Jan  2 17:14 compose
drwxr-xr-x   8 jon  staff    256 Jan  2 17:14 data
-rw-r--r--   1 jon  staff  12814 Jan  8 13:48 docker-compose.yml
drwxr-xr-x  38 jon  staff   1216 Jan  2 17:14 docs
drwxr-xr-x  10 jon  staff    320 Jan  7 15:59 log
drwxr-xr-x@  4 jon  staff    128 Jan  3 11:18 mail
drwxr-xr-x   9 jon  staff    288 Jan  2 17:14 mod
-rw-r--r--   1 jon  staff     86 Jan  2 17:14 shell.bat
-rwxr-xr-x   1 jon  staff     59 Jan  2 17:14 shell.sh
-rwxr-xr-x   1 jon  staff   2375 Jan  2 17:14 update-docker.sh
```

```
drwxr-xr-x@ 8 jon  staff  256 Jan  7 10:54 .
drwxr-xr-x@ 7 jon  staff  224 Jan  7 12:42 ..
-rw-r--r--  1 jon  staff  675 Jan  7 11:26 README.md
drwxr-xr-x  3 jon  staff   96 Jan  3 14:37 flagship
```

**Comment by cytopia** [comment]
Hi @jondkelley ,

thanks for the clear bug report!

I would first suggest to only add your service section to `docker-compose.override.yml`. Everything else was already defined in `docker-compose.yml` and there's no need to duplicate it. There might be some issues with the network duplication.

So it should look similar to this:
```yml
version: '2.1'
services:
  mysql_seed:
    image: flagship_mysql_seed:v1
    build: ../mysql_seeder
    environment:
      - MYSQL_DATABASE=flagship_local
      - MYSQL_USER=root
      - MYSQL_PASSWORD
      - MYSQL_SEED_BASE=base.sql.tar.gz
      - MYSQL_SEED_TRANSFORM=seed-dev.sql
      - MYSQL_GRANTS_FILE=grants.sql
    dns:
      - 172.16.238.100

    # MacOS and Windows have this by default, this hack also allows it for Linux
    extra_hosts:
      docker.for.lin.host.internal: 172.16.238.1
      docker.for.lin.localhost: 172.16.238.1

    networks:
      app_net:
        ipv4_address: 172.16.238.46
    depends_on:
      - mysql
      - php
      - httpd
      - bind
    # env_file:
    #  - ./env_vars
```

See docs for more details: https://devilbox.readthedocs.io/en/latest/advanced/add-your-own-docker-image.html
