### ISSUE TITLE
Persist bash/zsh history

### ISSUE THREAD

**Issue by Luc45** [cytopia/devilbox#694]
#### ISSUE TYPE

 - Feature request

#### SUMMARY
When running `docker-compose exec --user devilbox php bash -l`, every time you exit the container you lose the history of commands you typed. This is frustrating because I run a lot of tests, phpcs and phpcbf commands that I don't want to lose and have to type again.

When running `docker-compose exec --user devilbox php zsh -l`, it's slightly worse, because it always asks for a "first-time setup" every time you enter the container.

#### Goal
I'd like the history to persist when using bash or zsh inside the containers.

**Comment by science695** [comment]
@Luc45 The bash history does persist between repeated calls to bash or zsh. What clears it is a ./rebuild.sh because that literally deletes your running instance and rebuilds it.

If you wish your bash_history file to be preserved you can map it to a file in your devilbox (or create a volume for it if you hit performance issues).

docker-compose.overrides.yml:
```
php:
  volumes:
    - ${DEVILBOX_PATH}/bash_history:/home/devilbox/.bash_history
```
If you need to add it as a volume:
docker-compose.overrides.yml:
```
php:
  volumes:
    - devilbox-bash-history:/home/devilbox/.bash_history
volumes:
  devilbox-bash-history:
```
@cytopia This type of override may be useful for other circumstances, and may help others if a section for it was added to the docs. Feel free to steal anything from these examples if it helps.

**Comment by Luc45** [comment]
Thanks a lot @science695 !

I've ended up sharing the whole home directory, like this:
```
version: '2.3'
services:
  php:
    volumes:
      - ${PWD}/home_lucas:/home/devilbox
```
Because sharing individual files was causing them to be interpreted as folders, not sure why. But sharing the home folder worked nicely!
