### ISSUE TITLE
Move backups out of the Devilbox

### ISSUE THREAD

**Issue by llaville** [cytopia/devilbox#707]
#### ISSUE TYPE

 - Feature request

#### SUMMARY
Following the [Best Practice](https://devilbox.readthedocs.io/en/latest/intermediate/best-practice.html#move-data-out-of-devilbox-directory) to move data out of the Devilbox, I would like to have the same way for backups.

#### Goal

To do it, I've : 

- added a non official `HOST_PATH_BACKUPDIR` env var in my `.env` file 
- added a `docker-compose.override.yml` file with such content

```yaml
# IMPORTANT: The version must match the version of docker-compose.yml
---
version: '2.3'

services:
  php:
    volumes:
      # Mount Backup directory
      - ${HOST_PATH_BACKUPDIR}:/shared/backups:rw${MOUNT_OPTIONS}
```
