### ISSUE TITLE
Email catch-all: Delete entries within control center

### ISSUE THREAD

**Issue by fkaminski** [cytopia/devilbox#754]
It would be nice if we could delete one or all e-mail entries directly from the control center (instead manually in the console/shell).

**Comment by fkaminski** [comment]
Maybe leave a hint in the documentation for manually deleting mails too;
```
bash shell.sh
cd ../../var/mail
ls -a
rm devilbox
exit
```

**Comment by fkaminski** [comment]
Would still be a nice feature ...

**Comment by cytopia** [comment]
Agree

**Comment by llaville** [comment]
Probably you didn't notice yet but Mailhog is able to delete one or all messages in a GUI.
Of course as the default storage is in-memory, we have to configure it to use maildir storage (see https://github.com/mailhog/MailHog/blob/master/docs/CONFIG.md, the `MH_STORAGE` env variable).

Devilbox documentation about Mailhog is available at https://devilbox.readthedocs.io/en/latest/custom-container/enable-mailhog.html

And here is what the [current service](https://github.com/cytopia/devilbox/blob/master/compose/docker-compose.override.yml-mailhog) become when we use maildir storage with devilbox `backups/mailhog` directory (for example).

```yaml
# vim: set ft=yaml:
---
version: '2.3'

services:

  # -----------------------------------------------------------------------------------------------
  # MailHog
  # -----------------------------------------------------------------------------------------------
  mailhog:
    image: mailhog/mailhog:${MAILHOG_SERVER:-latest}
    hostname: mailhog
    ports:
      - "${LOCAL_LISTEN_ADDR}${HOST_PORT_MAILHOG:-8025}:8025"
    environment:
      MH_STORAGE: "maildir"
      MH_MAILDIR_PATH: /tmp/mailhog
    networks:
      app_net:
        ipv4_address: 172.16.238.201
    depends_on:
      - bind
      - php
      - httpd
    volumes:
      - ./backups/mailhog:/tmp/mailhog      
```

Usage of Mailhog allow to bypass issue #798. Remember that native devilbox mail support use a solution around PEAR that is a bit outdated now !
