### ISSUE TITLE
[Feature]: Add mercure.rocks addionnal container

### ISSUE THREAD

**Issue by TheoD02** [cytopia/devilbox#903]
### What is your idea or feature suggestion?

Add support of mercure.rocks in devilbox to add more possibilities for developers with new features

### Benefits

Allow user to make her application more live.

### Where can we find information about this?

[https://mercure.rocks/](https://mercure.rocks/)

# docker-compose.yml
```
version: "3.7"

services:
  caddy:
    image: dunglas/mercure
    restart: unless-stopped
    environment:
      # Uncomment the following line to disable HTTPS
      #SERVER_NAME: ':80'
      MERCURE_PUBLISHER_JWT_KEY: '!ChangeMe!'
      MERCURE_SUBSCRIBER_JWT_KEY: '!ChangeMe!'
    # Uncomment the following line to enable the development mode
    #command: /usr/bin/caddy run -config /etc/caddy/Caddyfile.dev
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:
```

### Are you willing to provide a PR to address this?

No
