### ISSUE TITLE
[Feature]: Add/migrate to mailpit

### ISSUE THREAD

**Issue by Sidlegionair** [cytopia/devilbox#970]
### What is your idea or feature suggestion?

Hey,

Can we migrate from supporting mailhog to mailpit? This one is included by default in the laravel 10.x .env and according to the mailpit project page: "Mailpit is inspired by [MailHog](https://github.com/axllent/mailpit#why-rewrite-mailhog), but much, much faster."

### Benefits

You can view the benefits here: https://github.com/axllent/mailpit#why-rewrite-mailhog

### Where can we find information about this?

https://github.com/axllent/mailpit

### Are you willing to provide a PR to address this?

None

**Comment by timo002** [comment]
It would be great if this is the default since mailhog is not developed anymore and not available for Apple Silicon.

I enabled mailpit by doing the following:

In `docker-compose.override.yml`
```
  # -----------------------------------------------------------------------------------------------
  # Mailpit
  # -----------------------------------------------------------------------------------------------
  mailpit:
    image: axllent/mailpit:${MAILPIT_SERVER:-latest}
    hostname: mailpit
    ports:
      - "${LOCAL_LISTEN_ADDR}${HOST_PORT_MAILPIT:-8025}:8025"
    networks:
      app_net:
        ipv4_address: 172.16.238.201
    depends_on:
      - bind
      - php
      - httpd
```

In the `.env` (devilbox) file
```
HOST_PORT_MAILPIT=8025
MAILPIT_SERVER=latest
```

I'm running symfony on devilbox, so in the `.env` file from symfony I added:
```
MAILER_DSN=smtp://mailpit:1025
```
This will do the trick and you can access mailpit on http://127.0.0.1:8025
